name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-versions: ['7.2', '7.3']

    name: ${{ matrix.os }} PHP ${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v2

      - name: Starting worflow!
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the event ${{ github.event_name }} done by ${{ github.actor }}"

      - name: 😊 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: make composer-install

#      - name: Install application dependencies
#        run: composer install --ignore-platform-reqs

      - name: Generate Laravel Key
        run: php artisan key:generate

      - name: Run the tests
        run: composer phpunit

